---
version: '3'

services:
  sbtemp:
    image: jcostom/sbtemp:latest
    container_name: sbtemp
    restart: unless-stopped
    environment:
      PLUG_IP: FIXME-IP-ADDR
      DAY_LOW: 65
      DAY_HIGH: 69
      NIGHT_LOW: 62
      NIGHT_HIGH: 66
      NIGHT_BEGIN: '22:00'
      NIGHT_END: '06:00'
      SLEEP_TIME: 300
      APIKEY: FIXME-APIKEY
      DEVID: FIXME-DEVID
      TZ: America/New_York
      INFLUX_BUCKET: FIXME
      INFLUX_ORG: FIXME
      INFLUX_TOKEN: 'FIXME'
      INFLUX_URL: 'http://FIXME:8086/'
      INFLUX_MEASUREMENT: FIXME
    networks:
      - containers

networks:
  containers:
    external: true

# or, if you don't already have that network defined, you could do it in this compose file.
# networks:
#   containers:
#     name: containers
#     driver: bridge
#     attachable: true
#     driver_opts:
#       com.docker.network.bridge.name: br-containers